'use client';

import * as React from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import {
  flexRender,
  getCoreRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  getFilteredRowModel,
  useReactTable,
  SortingState,
  ColumnFiltersState,
} from '@tanstack/react-table';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { useToast } from '@/hooks/use-toast';
import * as EventService from '@/lib/services/event.client.service'; // Use service namespace
import { EventAttendee, User } from '@/lib/types'; // Import User type
import { getAttendeeColumns } from './attendees-columns'; // Import columns from separate file
import { useUser } from '@/context/user-provider'; // Import useUser hook

interface AttendeeDataTableProps {
  attendees: EventAttendee[];
  eventId: string;
  sessionId: string;
  canManage: boolean;
}
export default function AttendeeDataTable({
  attendees,
  eventId,
  sessionId,
  canManage,
}: AttendeeDataTableProps) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [sorting, setSorting] = React.useState<SortingState>([]);
  const [columnFilters, setColumnFilters] = React.useState<ColumnFiltersState>([]);
  const { user: currentUser } = useUser(); // Call useUser hook

  const mutationOptions = (successMessage: string, queryKey: (string|undefined)[]) => ({
    onSuccess: () => {
      toast({ title: 'Success', description: successMessage });
      queryClient.invalidateQueries({ queryKey });
    },
    onError: (err: Error) => toast({ title: 'Error', description: err.message, variant: 'destructive' }),
  });

  const approveMutation = useMutation({
    mutationFn: EventService.approveRegistration,
    ...mutationOptions('Registration approved.', ['event-attendees', eventId, sessionId]),
  });

  const checkinMutation = useMutation({
    mutationFn: EventService.manualCheckin,
    ...mutationOptions('User checked in manually.', ['event-attendees', eventId, sessionId]),
  });

  const removeMutation = useMutation({
    mutationFn: (registrationId: string) => EventService.unregisterFromEvent(eventId, registrationId),
    ...mutationOptions('Attendee removed.', ['event-attendees', eventId, sessionId]),
  });
  
  // Columns are now generated by a separate, dedicated function.
  // This makes the main component cleaner and focused on table state.
  const columns = React.useMemo(
    () => getAttendeeColumns({
      canManage,
      approveMutation,
      checkinMutation,
      removeMutation,
      eventId,
      sessionId,
      currentUser, // Pass currentUser to getAttendeeColumns
    }),
    [canManage, approveMutation, checkinMutation, removeMutation, eventId, sessionId, currentUser]
  );

  const table = useReactTable({
    data: attendees,
    columns,
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    state: {
      sorting,
      columnFilters,
    },
  });

  return (
    <div className="w-full">
      <div className="flex items-center py-4">
        <Input
          placeholder="Filter by email..."
          value={(table.getColumn('user_email')?.getFilterValue() as string) ?? ''}
          onChange={(event) => table.getColumn('user_email')?.setFilterValue(event.target.value)}
          className="max-w-sm"
        />
      </div>
      <div className="rounded-md border">
        <Table>
          <TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => (
                  <TableHead key={header.id}>
                    {header.isPlaceholder
                      ? null
                      : flexRender(header.column.columnDef.header, header.getContext())}
                  </TableHead>
                ))}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {table.getRowModel().rows?.length ? (
              table.getRowModel().rows.map((row) => (
                <TableRow key={row.id}>
                  {row.getVisibleCells().map((cell) => (
                    <TableCell key={cell.id}>
                      {flexRender(cell.column.columnDef.cell, cell.getContext())}
                    </TableCell>
                  ))}
                </TableRow>
              ))
            ) : (
              <TableRow>
                <TableCell colSpan={columns.length} className="h-24 text-center">
                  No attendees found.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>
      <div className="flex items-center justify-end space-x-2 py-4">
        <Button
          variant="outline"
          size="sm"
          onClick={() => table.previousPage()}
          disabled={!table.getCanPreviousPage()}
        >
          Previous
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => table.nextPage()}
          disabled={!table.getCanNextPage()}
        >
          Next
        </Button>
      </div>
    </div>
  );
}
